version: '3.1'
services:
  backend:
    image: aergoscan/api:1.0.3
    build:
      args:
        ARG_SELECTED_NETWORK: testnet
        ARG_ES_URL: localhost:9200
    command:
      - docker run -d --rm -p 3000:3000 --net=host --privileged --name aergoscan-api aergoscan/api:1.0.3



