FROM node:14
LABEL email="cwlim@blocko.io"
LABEL description="aergoscan 2.0 api"

ARG ARG_SELECTED_NETWORK
ARG ARG_ES_URL
ARG ARG_HTTP_PORT

ENV SELECTED_NETWORK ${ARG_SELECTED_NETWORK}
ENV ES_URL ${ARG_ES_URL}
ENV HTTP_PORT ${ARG_HTTP_PORT}

WORKDIR /aergoscan-api
COPY package* ./
RUN npm install
COPY . .

ENTRYPOINT SELECTED_NETWORK=${SELECTED_NETWORK} ES_URL=${ES_URL} HTTP_PORT=${HTTP_PORT} node bin/server.js
EXPOSE ${HTTP_PORT}
