version: '3.1'
services:
  backend:
    image: aergoscan/api:1.0.0
    container_name: aergoscan-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ARG_SELECTED_NETWORK: testnet
        ARG_ES_URL: localhost:9200
        ARG_HTTP_PORT: 3000
    restart: always
    network_mode: host
    privileged: true
    command:
      - docker run -d --rm -p 3000:3000 --net=host --privileged --name aergoscan-api aergoscan/api:1.0.0



